config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web =>'/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  match 'users/:id/finish_sign_up', to: 'users#finish_sign_up', via: [:get, :patch], as: :finish_sign_up

  root to: 'questions#index'

  get '/search', to: 'search#search'

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      patch 'select_best', on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :awards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord

  include FilesAttachable
  include LinksAttachable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_one :award, dependent: :destroy

  accepts_nested_attributes_for :award, reject_if: :all_blank

  belongs_to :author, class_name: 'User'
  validates :title, :body, presence: true

  after_create :calculate_reputation

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  def index
    render json: questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: question
  end

  def create
    authorize! :create, Question

    question = Question.new(question_params)
    question.author = current_resource_owner

    if question.save
      render json: question, status: :created
    else
      render json: question.errors, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, question

    if question.update(question_params)
      render json: question, status: :ok
    else
      render json: question.errors, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, question

    question.destroy
  end

  private

  def questions
    @questions ||= Question.all
  end

  def question
    @question ||= Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :questions_author!, only: %i[update destroy]

  after_action :publish_question, only: %i[create]

  include Voted

  authorize_resource

  def index
    authorize! :read, Question
    @questions = Question.all
  end

  def show
    @answers = question.answers.includes(:links).with_attached_files.order(best: :desc)
    @answer = question.answers.new
    @answer.links.new
    @comment = Comment.new

    gon.push question_id: question.id
    gon.push user_id: current_user&.id
  end

  def new
    question.links.build
    @award = question.build_award
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params)
    flash.now[:notice] = 'Question was updated.'
  end

  def destroy
    question.destroy
    redirect_to questions_path, notice: 'Question was deleted.'
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
        'questions',
        { question: question }
    )
  end

  def questions_author!
    head :forbidden unless current_user&.author_of?(question)
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def answer
    @answer = question.answers.new
  end

  helper_method :question, :subscription

  def subscription
    @subscription ||= question.subscriptions.find_by(user: current_user)
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                     files: [], links_attributes: %i[id name url _destroy],
                                     award_attributes: %i[name image])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_edit_form.html.slim
= form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_field :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'partials/link_fields'
  = f.submit 'Save question'

app/views/questions/_form.html.slim
= form_with model: question, local: true do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  #question-links
    = f.fields_for :links do |link|
      = render 'partials/link_fields',  f: link
    .links
      = link_to_add_association 'add link', f, :links, partial: 'partials/link_fields'
  p Award:
  p
    = f.fields_for :award do |b|
      p
        = b.label :name
        = b.text_field :name
      p
        = b.label :image
        = b.file_field :image
  p= f.submit 'Ask'

app/views/questions/_question.html.slim
- cache collection_cache_key_for :question do
  .col-4.col-md-6
    h5.question-title
      p Question title ||
      = link_to question.title, question_path(question)
    h6
      | Question id
      = "#{question.id}"

app/views/questions/_question_partial.html.slim
- cache question do
  h1 = question.title
  h2 = question.body

  .files
    = render 'partials/files_block', resource: question
  br

  .links
    = render 'partials/links_block', resource: question

  br

  - if can?(:create, Subscription)
    .subscribe-option
      = render 'subscriptions/subscription', resource: question

  - if current_user&.author_of?(question)
    = link_to 'Edit question', '#', class: 'edit-question-link', data: {question_id: question.id}
    '  |
    = link_to 'Delete question', question_path(question), method: :delete

    = render 'edit_form'

  . class="question-#{question.id}"
    .voting
      - if user_signed_in?
        = render 'votes/vote', resource: question

    .comment-block
      = render 'comments/form', resource: question

app/views/questions/index.html.slim
.questions-index.row.d-flex.justify-content-center
  .col-sm-8.justify-content-center
    .card
      .card-header.bg-light.d-flex.justify-content-center
        h5 Check out available questions!
        .card-body
          .row.questions
            = render @questions

          - if can?(:create, Question)
            p= link_to 'Ask question', new_question_path, class: 'nav-link'

app/views/questions/new.html.slim
= render 'shared/errors', resource: question
= render 'form'

app/views/questions/show.html.slim
.question[data-id="#{question.id}"]
  .question-errors
  = render 'question_partial'

.answers
  .answer-errors
  .answer-update-errors
  = render @answers
- if user_signed_in?
  = render 'answers/form'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: question %>');

<% if !question.errors.present? %>
  $('.flash').append('<%= j render 'shared/flash' %>');
  $('.question').html('<%= j render 'question_partial' %>');
<% end %>