config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web =>'/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  match 'users/:id/finish_sign_up', to: 'users#finish_sign_up', via: [:get, :patch], as: :finish_sign_up

  root to: 'questions#index'

  get '/search', to: 'search#search'

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: %i[votable commentable] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, shallow: true, only: %i[create update destroy], concerns: %i[votable commentable] do
      patch 'select_best', on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :awards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord

  include FilesAttachable
  include LinksAttachable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :author, class_name: 'User'

  validates :body, presence: true

  after_create :notify_about_new_answer

  scope :sort_by_best, -> { order(best: :desc) }

  def set_the_best
    self.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      question.award&.update!(user: author)
    end
  end

  private

  def notify_about_new_answer
    NewAnswerNotifierJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :answers_author!, only: %i[update destroy]
  after_action :publish_answer, only: %i[create]

  include Voted

  authorize_resource

  def create
    @answer = question.answers.new(answer_params)
    @answer.author = current_user
    if @answer.save
      flash.now[:notice] = 'Your answer was successfully created.'
    end
  end

  def update
    authorize @answer
    @question = answer.question
    answer.update(answer_params)
    flash.now[:notice] = 'Your answer was successfully updated.'
  end

  def destroy
    @question = answer.question
    answer.destroy
    flash.now[:alert] = 'Answer was deleted.'
  end

  def select_best
    if current_user.author_of?(answer.question)
      answer.set_the_best
      @question = answer.question
    else
      head 403
    end
  end

  private

  def answers_author!
    head :forbidden unless current_user&.author_of?(answer)
  end

  def question
    @question ||= params[:question_id] ? Question.with_attached_files.find(params[:question_id]) : nil
  end

  def answer
    @answer ||= params[:id] ? Answer.find(params[:id]) : Answer.new
  end

  helper_method :question, :answer

  def answer_params
    params.require(:answer).permit(:body,
                                   files: [], links_attributes: [:name, :url])
  end

  def publish_answer
    return if @answer.errors.any?

    files = []
    answer.files.each do |file|
      files << { url: url_for(file), name: file.filename.to_s }
    end

    ActionCable.server.broadcast(
        "answer_for_question_#{answer.question_id}",
        { answer: answer,
          links: answer.links,
          files: files }
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  authorize_resource

  def index
    render json: answers, each_serialized: AnswersSerializer
  end

  def show
    render json: answer
  end

  def create
    authorize! :create, Answer

    answer = question.answers.build(answer_params)
    answer.author = current_resource_owner

    if answer.save
      render json: answer, status: :created
    else
      render json: answer.errors, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, answer

    if answer.update(answer_params)
      render json: answer, status: :ok
    else
      render json: answer.errors, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, answer

    answer.destroy
  end

  private

  def answers
    @answers ||= Answer.all
  end

  def answer
    @answer ||= Answer.find(params[:id])
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  . class="answer-#{answer.id}"

    p = answer.body

    .comment-block
      = render 'comments/form', resource: answer

    .voting
      - if user_signed_in?
        = render 'votes/vote', resource: answer

    br
    .files
      = render 'partials/files_block', resource: answer
    br
    .answer-links
      = render 'partials/links_block', resource: answer

    - if current_user&.author_of?(answer.question)
      = link_to 'Set the Best', select_best_answer_path(answer), method: :patch, remote: true, class: 'best-answer'
      '  |
    - if current_user&.author_of?(answer) && answer.persisted?
      = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
      '  |
      = link_to 'Edit', '#', class: 'edit-answer-link', data: {answer_id: answer.id}, remote: true

    = render partial: 'answers/edit_form', locals: {answer: answer}

app/views/answers/_edit_form.html.slim
= form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
  p
    = f.label :body, 'Your answer'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'partials/link_fields'
  p
    = f.submit 'Save'

app/views/answers/_form.html.slim
= form_with model: [question, @answer], class: 'answer-body', data: { type: :json } do |f|
  .field
    = f.label :body, 'Answer body'
    = f.text_area :body
  .field
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  #answer-links
    = f.fields_for :links do |link|
      = render 'partials/link_fields', f: link
    .links
      = link_to_add_association 'additional link', f, :links, partial: 'partials/link_fields'
  .submit
    = f.submit 'Create answer'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');
<% if answer.persisted? %>
  $('.flash').append('<%= j render 'shared/flash' %>');
  $('.answers').append('<%= j render answer %>');
  $('.answer-body #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.flash').html('<%= render 'shared/flash' %>').delay(2000).fadeOut('slow');
$('.answer-<%= answer.id %>').remove();

app/views/answers/select_best.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');
$('.answer-<%= answer.id %>').remove();
$('.answers').prepend('<%= j render answer %>');

app/views/answers/update.js.erb
$('.answer-update-errors').html('<%= render 'shared/errors', resource: answer %>');
<% if !answer.errors.present? %>
  $('.flash').append('<%= render 'shared/flash' %>').delay(1000).fadeOut('slow');
  $('.answers').first('.answer-<%= answer.id %>').html('<%= j render answer %>');
<% end %>